# -*- coding: utf-8 -*-
######################################################################################################################
# Copyright (C) 2017-2020 Spine project consortium
# This file is part of Spine Toolbox.
# Spine Toolbox is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
# Public License for more details. You should have received a copy of the GNU Lesser General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
######################################################################################################################

# Form implementation generated from reading ui file 'C:\data\GIT\SPINETOOLBOX\bin\..\spinetoolbox\ui\data_store_view.ui',
# licensing of 'C:\data\GIT\SPINETOOLBOX\bin\..\spinetoolbox\ui\data_store_view.ui' applies.
#
# Created: Thu Feb 13 11:53:56 2020
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 814)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 28))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuSession = QtWidgets.QMenu(self.menubar)
        self.menuSession.setObjectName("menuSession")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuGraph = QtWidgets.QMenu(self.menubar)
        self.menuGraph.setObjectName("menuGraph")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_parameter_value_list = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_parameter_value_list.setObjectName("dockWidget_parameter_value_list")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView_parameter_value_list = CopyTreeView(self.dockWidgetContents)
        self.treeView_parameter_value_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView_parameter_value_list.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeView_parameter_value_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView_parameter_value_list.setUniformRowHeights(True)
        self.treeView_parameter_value_list.setObjectName("treeView_parameter_value_list")
        self.verticalLayout.addWidget(self.treeView_parameter_value_list)
        self.dockWidget_parameter_value_list.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_parameter_value_list)
        self.dockWidget_relationship_parameter_value = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_relationship_parameter_value.setObjectName("dockWidget_relationship_parameter_value")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_relationship_parameter_value = AutoFilterCopyPasteTableView(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_relationship_parameter_value.sizePolicy().hasHeightForWidth())
        self.tableView_relationship_parameter_value.setSizePolicy(sizePolicy)
        self.tableView_relationship_parameter_value.setMouseTracking(True)
        self.tableView_relationship_parameter_value.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_relationship_parameter_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_relationship_parameter_value.setTabKeyNavigation(False)
        self.tableView_relationship_parameter_value.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_relationship_parameter_value.setSortingEnabled(False)
        self.tableView_relationship_parameter_value.setWordWrap(False)
        self.tableView_relationship_parameter_value.setObjectName("tableView_relationship_parameter_value")
        self.tableView_relationship_parameter_value.horizontalHeader().setHighlightSections(False)
        self.tableView_relationship_parameter_value.verticalHeader().setVisible(False)
        self.tableView_relationship_parameter_value.verticalHeader().setHighlightSections(False)
        self.verticalLayout_5.addWidget(self.tableView_relationship_parameter_value)
        self.dockWidget_relationship_parameter_value.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_relationship_parameter_value)
        self.dockWidget_object_parameter_value = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_object_parameter_value.setObjectName("dockWidget_object_parameter_value")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView_object_parameter_value = AutoFilterCopyPasteTableView(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_object_parameter_value.sizePolicy().hasHeightForWidth())
        self.tableView_object_parameter_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tableView_object_parameter_value.setFont(font)
        self.tableView_object_parameter_value.setMouseTracking(True)
        self.tableView_object_parameter_value.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_object_parameter_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_object_parameter_value.setTabKeyNavigation(False)
        self.tableView_object_parameter_value.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_object_parameter_value.setSortingEnabled(False)
        self.tableView_object_parameter_value.setWordWrap(False)
        self.tableView_object_parameter_value.setObjectName("tableView_object_parameter_value")
        self.tableView_object_parameter_value.horizontalHeader().setHighlightSections(False)
        self.tableView_object_parameter_value.verticalHeader().setVisible(False)
        self.tableView_object_parameter_value.verticalHeader().setHighlightSections(False)
        self.tableView_object_parameter_value.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_3.addWidget(self.tableView_object_parameter_value)
        self.dockWidget_object_parameter_value.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_object_parameter_value)
        self.dockWidget_object_parameter_definition = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_object_parameter_definition.setObjectName("dockWidget_object_parameter_definition")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableView_object_parameter_definition = AutoFilterCopyPasteTableView(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_object_parameter_definition.sizePolicy().hasHeightForWidth())
        self.tableView_object_parameter_definition.setSizePolicy(sizePolicy)
        self.tableView_object_parameter_definition.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_object_parameter_definition.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_object_parameter_definition.setTabKeyNavigation(False)
        self.tableView_object_parameter_definition.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_object_parameter_definition.setSortingEnabled(False)
        self.tableView_object_parameter_definition.setWordWrap(False)
        self.tableView_object_parameter_definition.setObjectName("tableView_object_parameter_definition")
        self.tableView_object_parameter_definition.horizontalHeader().setHighlightSections(False)
        self.tableView_object_parameter_definition.horizontalHeader().setSortIndicatorShown(False)
        self.tableView_object_parameter_definition.verticalHeader().setVisible(False)
        self.tableView_object_parameter_definition.verticalHeader().setHighlightSections(False)
        self.verticalLayout_8.addWidget(self.tableView_object_parameter_definition)
        self.dockWidget_object_parameter_definition.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_object_parameter_definition)
        self.dockWidget_relationship_parameter_definition = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_relationship_parameter_definition.setObjectName("dockWidget_relationship_parameter_definition")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableView_relationship_parameter_definition = AutoFilterCopyPasteTableView(self.dockWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_relationship_parameter_definition.sizePolicy().hasHeightForWidth())
        self.tableView_relationship_parameter_definition.setSizePolicy(sizePolicy)
        self.tableView_relationship_parameter_definition.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_relationship_parameter_definition.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_relationship_parameter_definition.setTabKeyNavigation(False)
        self.tableView_relationship_parameter_definition.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_relationship_parameter_definition.setSortingEnabled(False)
        self.tableView_relationship_parameter_definition.setWordWrap(False)
        self.tableView_relationship_parameter_definition.setObjectName("tableView_relationship_parameter_definition")
        self.tableView_relationship_parameter_definition.horizontalHeader().setHighlightSections(False)
        self.tableView_relationship_parameter_definition.verticalHeader().setVisible(False)
        self.tableView_relationship_parameter_definition.verticalHeader().setHighlightSections(False)
        self.verticalLayout_10.addWidget(self.tableView_relationship_parameter_definition)
        self.dockWidget_relationship_parameter_definition.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_relationship_parameter_definition)
        self.dockWidget_object_tree = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_object_tree.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget_object_tree.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget_object_tree.setObjectName("dockWidget_object_tree")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeView_object = StickySelectionEntityTreeView(self.dockWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_object.sizePolicy().hasHeightForWidth())
        self.treeView_object.setSizePolicy(sizePolicy)
        self.treeView_object.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView_object.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeView_object.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView_object.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeView_object.setIconSize(QtCore.QSize(20, 20))
        self.treeView_object.setUniformRowHeights(True)
        self.treeView_object.setObjectName("treeView_object")
        self.verticalLayout_4.addWidget(self.treeView_object)
        self.dockWidget_object_tree.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_object_tree)
        self.dockWidget_relationship_tree = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_relationship_tree.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_relationship_tree.setObjectName("dockWidget_relationship_tree")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents_7)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.treeView_relationship = EntityTreeView(self.dockWidgetContents_7)
        self.treeView_relationship.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView_relationship.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeView_relationship.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView_relationship.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeView_relationship.setIconSize(QtCore.QSize(20, 20))
        self.treeView_relationship.setUniformRowHeights(True)
        self.treeView_relationship.setObjectName("treeView_relationship")
        self.verticalLayout_6.addWidget(self.treeView_relationship)
        self.dockWidget_relationship_tree.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_relationship_tree)
        self.dockWidget_entity_graph = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_entity_graph.setObjectName("dockWidget_entity_graph")
        self.dockWidgetContents_8 = QtWidgets.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dockWidgetContents_8)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.graphicsView = GraphQGraphicsView(self.dockWidgetContents_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_7.addWidget(self.graphicsView)
        self.dockWidget_entity_graph.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_entity_graph)
        self.dockWidget_item_palette = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_item_palette.setObjectName("dockWidget_item_palette")
        self.dockWidgetContents_9 = QtWidgets.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.dockWidgetContents_9)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.splitter_object_relationship_class = QtWidgets.QSplitter(self.dockWidgetContents_9)
        self.splitter_object_relationship_class.setOrientation(QtCore.Qt.Vertical)
        self.splitter_object_relationship_class.setObjectName("splitter_object_relationship_class")
        self.frame = QtWidgets.QFrame(self.splitter_object_relationship_class)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.listView_object_class = DragListView(self.frame)
        self.listView_object_class.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listView_object_class.setFont(font)
        self.listView_object_class.setMouseTracking(True)
        self.listView_object_class.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listView_object_class.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_object_class.setProperty("showDropIndicator", False)
        self.listView_object_class.setDragEnabled(False)
        self.listView_object_class.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listView_object_class.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listView_object_class.setIconSize(QtCore.QSize(24, 24))
        self.listView_object_class.setTextElideMode(QtCore.Qt.ElideRight)
        self.listView_object_class.setMovement(QtWidgets.QListView.Static)
        self.listView_object_class.setFlow(QtWidgets.QListView.LeftToRight)
        self.listView_object_class.setProperty("isWrapping", True)
        self.listView_object_class.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView_object_class.setGridSize(QtCore.QSize(96, 48))
        self.listView_object_class.setViewMode(QtWidgets.QListView.IconMode)
        self.listView_object_class.setUniformItemSizes(False)
        self.listView_object_class.setWordWrap(True)
        self.listView_object_class.setSelectionRectVisible(True)
        self.listView_object_class.setObjectName("listView_object_class")
        self.verticalLayout_9.addWidget(self.listView_object_class)
        self.frame_2 = QtWidgets.QFrame(self.splitter_object_relationship_class)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.listView_relationship_class = DragListView(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listView_relationship_class.setFont(font)
        self.listView_relationship_class.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_relationship_class.setProperty("showDropIndicator", False)
        self.listView_relationship_class.setDragEnabled(False)
        self.listView_relationship_class.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listView_relationship_class.setIconSize(QtCore.QSize(24, 24))
        self.listView_relationship_class.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listView_relationship_class.setMovement(QtWidgets.QListView.Static)
        self.listView_relationship_class.setFlow(QtWidgets.QListView.LeftToRight)
        self.listView_relationship_class.setProperty("isWrapping", True)
        self.listView_relationship_class.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView_relationship_class.setGridSize(QtCore.QSize(96, 48))
        self.listView_relationship_class.setViewMode(QtWidgets.QListView.IconMode)
        self.listView_relationship_class.setUniformItemSizes(False)
        self.listView_relationship_class.setWordWrap(True)
        self.listView_relationship_class.setObjectName("listView_relationship_class")
        self.verticalLayout_11.addWidget(self.listView_relationship_class)
        self.verticalLayout_12.addWidget(self.splitter_object_relationship_class)
        self.dockWidget_item_palette.setWidget(self.dockWidgetContents_9)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_item_palette)
        self.dockWidget_pivot_table = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_pivot_table.setObjectName("dockWidget_pivot_table")
        self.dockWidgetContents_10 = QtWidgets.QWidget()
        self.dockWidgetContents_10.setObjectName("dockWidgetContents_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.dockWidgetContents_10)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_pivot_table_input_type = QtWidgets.QComboBox(self.dockWidgetContents_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pivot_table_input_type.sizePolicy().hasHeightForWidth())
        self.comboBox_pivot_table_input_type.setSizePolicy(sizePolicy)
        self.comboBox_pivot_table_input_type.setMaximumSize(QtCore.QSize(180, 23))
        self.comboBox_pivot_table_input_type.setObjectName("comboBox_pivot_table_input_type")
        self.horizontalLayout.addWidget(self.comboBox_pivot_table_input_type)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.pivot_table = PivotTableView(self.dockWidgetContents_10)
        self.pivot_table.setObjectName("pivot_table")
        self.verticalLayout_13.addWidget(self.pivot_table)
        self.dockWidget_pivot_table.setWidget(self.dockWidgetContents_10)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_pivot_table)
        self.dockWidget_frozen_table = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_frozen_table.setObjectName("dockWidget_frozen_table")
        self.dockWidgetContents_11 = QtWidgets.QWidget()
        self.dockWidgetContents_11.setObjectName("dockWidgetContents_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.dockWidgetContents_11)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frozen_table = FrozenTableView(self.dockWidgetContents_11)
        self.frozen_table.setObjectName("frozen_table")
        self.verticalLayout_14.addWidget(self.frozen_table)
        self.dockWidget_frozen_table.setWidget(self.dockWidgetContents_11)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_frozen_table)
        self.actionCommit = QtWidgets.QAction(MainWindow)
        self.actionCommit.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/menu_icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCommit.setIcon(icon)
        self.actionCommit.setObjectName("actionCommit")
        self.actionRollback = QtWidgets.QAction(MainWindow)
        self.actionRollback.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menu_icons/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRollback.setIcon(icon1)
        self.actionRollback.setObjectName("actionRollback")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/menu_icons/window-close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionClose.setObjectName("actionClose")
        self.actionAdd_object_classes = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/menu_icons/cube_plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_object_classes.setIcon(icon3)
        self.actionAdd_object_classes.setObjectName("actionAdd_object_classes")
        self.actionAdd_objects = QtWidgets.QAction(MainWindow)
        self.actionAdd_objects.setIcon(icon3)
        self.actionAdd_objects.setObjectName("actionAdd_objects")
        self.actionAdd_relationship_classes = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/menu_icons/cubes_plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_relationship_classes.setIcon(icon4)
        self.actionAdd_relationship_classes.setObjectName("actionAdd_relationship_classes")
        self.actionAdd_relationships = QtWidgets.QAction(MainWindow)
        self.actionAdd_relationships.setIcon(icon4)
        self.actionAdd_relationships.setObjectName("actionAdd_relationships")
        self.actionImport = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/project_item_icons/database-import.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon5)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/project_item_icons/database-export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon6)
        self.actionExport.setObjectName("actionExport")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/menu_icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon7)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setEnabled(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/menu_icons/paste.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon8)
        self.actionPaste.setObjectName("actionPaste")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/menu_icons/sync.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon9)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionEdit_object_classes = QtWidgets.QAction(MainWindow)
        self.actionEdit_object_classes.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/menu_icons/cube_pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_object_classes.setIcon(icon10)
        self.actionEdit_object_classes.setObjectName("actionEdit_object_classes")
        self.actionEdit_relationship_classes = QtWidgets.QAction(MainWindow)
        self.actionEdit_relationship_classes.setEnabled(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/menu_icons/cubes_pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_relationship_classes.setIcon(icon11)
        self.actionEdit_relationship_classes.setObjectName("actionEdit_relationship_classes")
        self.actionEdit_objects = QtWidgets.QAction(MainWindow)
        self.actionEdit_objects.setEnabled(True)
        self.actionEdit_objects.setIcon(icon10)
        self.actionEdit_objects.setObjectName("actionEdit_objects")
        self.actionEdit_relationships = QtWidgets.QAction(MainWindow)
        self.actionEdit_relationships.setEnabled(True)
        self.actionEdit_relationships.setIcon(icon11)
        self.actionEdit_relationships.setObjectName("actionEdit_relationships")
        self.actionManage_parameter_tags = QtWidgets.QAction(MainWindow)
        self.actionManage_parameter_tags.setObjectName("actionManage_parameter_tags")
        self.actionRemove_selection = QtWidgets.QAction(MainWindow)
        self.actionRemove_selection.setEnabled(True)
        self.actionRemove_selection.setObjectName("actionRemove_selection")
        self.actionHide_selected = QtWidgets.QAction(MainWindow)
        self.actionHide_selected.setObjectName("actionHide_selected")
        self.actionShow_hidden = QtWidgets.QAction(MainWindow)
        self.actionShow_hidden.setObjectName("actionShow_hidden")
        self.actionPrune_selected = QtWidgets.QAction(MainWindow)
        self.actionPrune_selected.setObjectName("actionPrune_selected")
        self.actionRestore_pruned = QtWidgets.QAction(MainWindow)
        self.actionRestore_pruned.setObjectName("actionRestore_pruned")
        self.actionLive_graph_demo = QtWidgets.QAction(MainWindow)
        self.actionLive_graph_demo.setObjectName("actionLive_graph_demo")
        self.actionTree_style = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/symbols/menu_icons/tree.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTree_style.setIcon(icon12)
        self.actionTree_style.setObjectName("actionTree_style")
        self.actionGraph_style = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/project-diagram.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGraph_style.setIcon(icon13)
        self.actionGraph_style.setObjectName("actionGraph_style")
        self.actionTabular_style = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/symbols/menu_icons/table.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTabular_style.setIcon(icon14)
        self.actionTabular_style.setObjectName("actionTabular_style")
        self.actionView_history = QtWidgets.QAction(MainWindow)
        self.actionView_history.setObjectName("actionView_history")
        self.menuSession.addAction(self.actionRefresh)
        self.menuSession.addAction(self.actionCommit)
        self.menuSession.addAction(self.actionRollback)
        self.menuSession.addSeparator()
        self.menuSession.addAction(self.actionView_history)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_object_classes)
        self.menuEdit.addAction(self.actionAdd_objects)
        self.menuEdit.addAction(self.actionAdd_relationship_classes)
        self.menuEdit.addAction(self.actionAdd_relationships)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionEdit_object_classes)
        self.menuEdit.addAction(self.actionEdit_objects)
        self.menuEdit.addAction(self.actionEdit_relationship_classes)
        self.menuEdit.addAction(self.actionEdit_relationships)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRemove_selection)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionManage_parameter_tags)
        self.menuEdit.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionTree_style)
        self.menuView.addAction(self.actionTabular_style)
        self.menuView.addAction(self.actionGraph_style)
        self.menuGraph.addAction(self.actionHide_selected)
        self.menuGraph.addAction(self.actionShow_hidden)
        self.menuGraph.addSeparator()
        self.menuGraph.addAction(self.actionPrune_selected)
        self.menuGraph.addAction(self.actionRestore_pruned)
        self.menuHelp.addAction(self.actionLive_graph_demo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())
        self.menubar.addAction(self.menuSession.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tableView_object_parameter_value, self.tableView_object_parameter_definition)
        MainWindow.setTabOrder(self.tableView_object_parameter_definition, self.tableView_relationship_parameter_value)
        MainWindow.setTabOrder(self.tableView_relationship_parameter_value, self.tableView_relationship_parameter_definition)
        MainWindow.setTabOrder(self.tableView_relationship_parameter_definition, self.treeView_parameter_value_list)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.menuSession.setTitle(QtWidgets.QApplication.translate("MainWindow", "Session", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuGraph.setTitle(QtWidgets.QApplication.translate("MainWindow", "Graph", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.dockWidget_parameter_value_list.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Parameter value list", None, -1))
        self.treeView_parameter_value_list.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "parameter value list", None, -1))
        self.dockWidget_relationship_parameter_value.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Relationship parameter value", None, -1))
        self.tableView_relationship_parameter_value.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "relationship parameter value", None, -1))
        self.dockWidget_object_parameter_value.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Object parameter value", None, -1))
        self.tableView_object_parameter_value.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "object parameter value", None, -1))
        self.dockWidget_object_parameter_definition.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Object parameter definition", None, -1))
        self.tableView_object_parameter_definition.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "object parameter definition", None, -1))
        self.dockWidget_relationship_parameter_definition.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Relationship parameter definition", None, -1))
        self.tableView_relationship_parameter_definition.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "relationship parameter definition", None, -1))
        self.dockWidget_object_tree.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Object tree", None, -1))
        self.treeView_object.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "object tree", None, -1))
        self.dockWidget_relationship_tree.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Relationship tree", None, -1))
        self.treeView_relationship.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "relationship tree", None, -1))
        self.dockWidget_entity_graph.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Entity graph", None, -1))
        self.dockWidget_item_palette.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Item palette", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Object class", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Relationship class", None, -1))
        self.dockWidget_pivot_table.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Pivot table", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Input type:", None, -1))
        self.dockWidget_frozen_table.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Frozen table", None, -1))
        self.actionCommit.setText(QtWidgets.QApplication.translate("MainWindow", "Commit", None, -1))
        self.actionCommit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Return", None, -1))
        self.actionRollback.setText(QtWidgets.QApplication.translate("MainWindow", "Rollback", None, -1))
        self.actionRollback.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Backspace", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))
        self.actionClose.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None, -1))
        self.actionAdd_object_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Add object classes", None, -1))
        self.actionAdd_object_classes.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add object classes", None, -1))
        self.actionAdd_objects.setText(QtWidgets.QApplication.translate("MainWindow", "Add objects", None, -1))
        self.actionAdd_objects.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add objects", None, -1))
        self.actionAdd_relationship_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Add relationship classes", None, -1))
        self.actionAdd_relationship_classes.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add relationship classes", None, -1))
        self.actionAdd_relationships.setText(QtWidgets.QApplication.translate("MainWindow", "Add relationships", None, -1))
        self.actionAdd_relationships.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add relationships", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.actionExport.setText(QtWidgets.QApplication.translate("MainWindow", "Export", None, -1))
        self.actionCopy.setText(QtWidgets.QApplication.translate("MainWindow", "Copy", None, -1))
        self.actionCopy.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+C", None, -1))
        self.actionPaste.setText(QtWidgets.QApplication.translate("MainWindow", "Paste", None, -1))
        self.actionPaste.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+V", None, -1))
        self.actionRefresh.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.actionRefresh.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F5", None, -1))
        self.actionEdit_object_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Edit object classes", None, -1))
        self.actionEdit_relationship_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Edit relationship classes", None, -1))
        self.actionEdit_objects.setText(QtWidgets.QApplication.translate("MainWindow", "Edit objects", None, -1))
        self.actionEdit_relationships.setText(QtWidgets.QApplication.translate("MainWindow", "Edit relationships", None, -1))
        self.actionManage_parameter_tags.setText(QtWidgets.QApplication.translate("MainWindow", "Manage parameter tags", None, -1))
        self.actionRemove_selection.setText(QtWidgets.QApplication.translate("MainWindow", "Remove selection", None, -1))
        self.actionRemove_selection.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Del", None, -1))
        self.actionHide_selected.setText(QtWidgets.QApplication.translate("MainWindow", "Hide selected", None, -1))
        self.actionShow_hidden.setText(QtWidgets.QApplication.translate("MainWindow", "Show hidden items", None, -1))
        self.actionPrune_selected.setText(QtWidgets.QApplication.translate("MainWindow", "Prune selected items", None, -1))
        self.actionRestore_pruned.setText(QtWidgets.QApplication.translate("MainWindow", "Restore pruned", None, -1))
        self.actionLive_graph_demo.setText(QtWidgets.QApplication.translate("MainWindow", "Live graph demo", None, -1))
        self.actionTree_style.setText(QtWidgets.QApplication.translate("MainWindow", "Tree style", None, -1))
        self.actionGraph_style.setText(QtWidgets.QApplication.translate("MainWindow", "Graph style", None, -1))
        self.actionTabular_style.setText(QtWidgets.QApplication.translate("MainWindow", "Tabular style", None, -1))
        self.actionView_history.setText(QtWidgets.QApplication.translate("MainWindow", "View history...", None, -1))

from spinetoolbox.widgets.custom_qtreeview import StickySelectionEntityTreeView, CopyTreeView, EntityTreeView
from spinetoolbox.widgets.custom_qlistview import DragListView
from spinetoolbox.widgets.custom_qtableview import PivotTableView, AutoFilterCopyPasteTableView
from spinetoolbox.widgets.frozen_table_view import FrozenTableView
from spinetoolbox.widgets.custom_qgraphicsviews import GraphQGraphicsView
from spinetoolbox import resources_icons_rc
