######################################################################################################################
# Copyright (C) 2017 - 2018 Spine project consortium
# This file is part of Spine Toolbox.
# Spine Toolbox is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
# Public License for more details. You should have received a copy of the GNU Lesser General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
######################################################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../spinetoolbox/ui/graph_view_form.ui',
# licensing of '../spinetoolbox/ui/graph_view_form.ui' applies.
#
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = GraphViewGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 25))
        self.menubar.setObjectName("menubar")
        self.menuGraph = QtWidgets.QMenu(self.menubar)
        self.menuGraph.setObjectName("menuGraph")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuDock_Widgets = QtWidgets.QMenu(self.menuView)
        self.menuDock_Widgets.setObjectName("menuDock_Widgets")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_item_list = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_item_list.setObjectName("dockWidget_item_list")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.listView_object = ObjectClassListView(self.splitter)
        self.listView_object.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listView_object.setFont(font)
        self.listView_object.setMouseTracking(True)
        self.listView_object.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_object.setProperty("showDropIndicator", False)
        self.listView_object.setDragEnabled(False)
        self.listView_object.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listView_object.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listView_object.setIconSize(QtCore.QSize(32, 32))
        self.listView_object.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listView_object.setMovement(QtWidgets.QListView.Static)
        self.listView_object.setFlow(QtWidgets.QListView.LeftToRight)
        self.listView_object.setProperty("isWrapping", True)
        self.listView_object.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView_object.setGridSize(QtCore.QSize(112, 64))
        self.listView_object.setViewMode(QtWidgets.QListView.IconMode)
        self.listView_object.setUniformItemSizes(False)
        self.listView_object.setWordWrap(True)
        self.listView_object.setSelectionRectVisible(True)
        self.listView_object.setObjectName("listView_object")
        self.listView_relationship = QtWidgets.QListView(self.splitter)
        self.listView_relationship.setProperty("showDropIndicator", False)
        self.listView_relationship.setDragEnabled(False)
        self.listView_relationship.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listView_relationship.setIconSize(QtCore.QSize(24, 24))
        self.listView_relationship.setViewMode(QtWidgets.QListView.ListMode)
        self.listView_relationship.setUniformItemSizes(True)
        self.listView_relationship.setWordWrap(True)
        self.listView_relationship.setObjectName("listView_relationship")
        self.verticalLayout_3.addWidget(self.splitter)
        self.dockWidget_item_list.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_item_list)
        self.dockWidget_item_tree = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_item_tree.setObjectName("dockWidget_item_tree")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeView)
        self.dockWidget_item_tree.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_item_tree)
        self.actionBuild = QtWidgets.QAction(MainWindow)
        self.actionBuild.setObjectName("actionBuild")
        self.actionDock_widgets = QtWidgets.QAction(MainWindow)
        self.actionDock_widgets.setObjectName("actionDock_widgets")
        self.actiontodos = QtWidgets.QAction(MainWindow)
        self.actiontodos.setObjectName("actiontodos")
        self.menuGraph.addAction(self.actionBuild)
        self.menuView.addAction(self.menuDock_Widgets.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.menuGraph.setTitle(QtWidgets.QApplication.translate("MainWindow", "Graph", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuDock_Widgets.setTitle(QtWidgets.QApplication.translate("MainWindow", "Dock Widgets", None, -1))
        self.dockWidget_item_list.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Item list", None, -1))
        self.dockWidget_item_tree.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Item tree", None, -1))
        self.actionBuild.setText(QtWidgets.QApplication.translate("MainWindow", "Rebuild", None, -1))
        self.actionBuild.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F5", None, -1))
        self.actionDock_widgets.setText(QtWidgets.QApplication.translate("MainWindow", "Dock Widgets", None, -1))
        self.actiontodos.setText(QtWidgets.QApplication.translate("MainWindow", "todos", None, -1))

from widgets.custom_qgraphicsview import GraphViewGraphicsView
from widgets.custom_qlistview import ObjectClassListView
