# -*- coding: utf-8 -*-
######################################################################################################################
# Copyright (C) 2017-2020 Spine project consortium
# This file is part of Spine Toolbox.
# Spine Toolbox is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
# Public License for more details. You should have received a copy of the GNU Lesser General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
######################################################################################################################

# Form implementation generated from reading ui file 'C:\data\GIT\SPINETOOLBOX\bin\..\spinetoolbox\ui\settings.ui',
# licensing of 'C:\data\GIT\SPINETOOLBOX\bin\..\spinetoolbox\ui\settings.ui' applies.
#
# Created: Thu Feb 13 11:54:11 2020
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName("SettingsForm")
        SettingsForm.setWindowModality(QtCore.Qt.ApplicationModal)
        SettingsForm.resize(700, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsForm.sizePolicy().hasHeightForWidth())
        SettingsForm.setSizePolicy(sizePolicy)
        SettingsForm.setMinimumSize(QtCore.QSize(700, 550))
        SettingsForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        SettingsForm.setMouseTracking(False)
        SettingsForm.setFocusPolicy(QtCore.Qt.StrongFocus)
        SettingsForm.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        SettingsForm.setAutoFillBackground(False)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(SettingsForm)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(SettingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(112, 16777215))
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setSpacing(0)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setSelectionRectVisible(True)
        self.listWidget.setObjectName("listWidget")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/sliders-h.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.listWidget)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/project-diagram.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.listWidget)
        item.setIcon(icon1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/tools.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.listWidget)
        item.setIcon(icon2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtWidgets.QListWidgetItem(self.listWidget)
        item.setIcon(icon3)
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(SettingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.General)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_general = QtWidgets.QGroupBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_general.sizePolicy().hasHeightForWidth())
        self.groupBox_general.setSizePolicy(sizePolicy)
        self.groupBox_general.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_general.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_general.setAutoFillBackground(False)
        self.groupBox_general.setFlat(False)
        self.groupBox_general.setObjectName("groupBox_general")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_general)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_open_previous_project = QtWidgets.QCheckBox(self.groupBox_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_open_previous_project.sizePolicy().hasHeightForWidth())
        self.checkBox_open_previous_project.setSizePolicy(sizePolicy)
        self.checkBox_open_previous_project.setObjectName("checkBox_open_previous_project")
        self.gridLayout.addWidget(self.checkBox_open_previous_project, 0, 0, 1, 1)
        self.checkBox_exit_prompt = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_exit_prompt.setTristate(False)
        self.checkBox_exit_prompt.setObjectName("checkBox_exit_prompt")
        self.gridLayout.addWidget(self.checkBox_exit_prompt, 1, 0, 1, 1)
        self.checkBox_save_at_exit = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_save_at_exit.setTristate(True)
        self.checkBox_save_at_exit.setObjectName("checkBox_save_at_exit")
        self.gridLayout.addWidget(self.checkBox_save_at_exit, 2, 0, 1, 1)
        self.checkBox_datetime = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_datetime.setObjectName("checkBox_datetime")
        self.gridLayout.addWidget(self.checkBox_datetime, 3, 0, 1, 1)
        self.checkBox_delete_data = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_delete_data.setObjectName("checkBox_delete_data")
        self.gridLayout.addWidget(self.checkBox_delete_data, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_general)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_work_dir = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_work_dir.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_work_dir.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_work_dir.setClearButtonEnabled(True)
        self.lineEdit_work_dir.setObjectName("lineEdit_work_dir")
        self.horizontalLayout_6.addWidget(self.lineEdit_work_dir)
        self.toolButton_browse_work = QtWidgets.QToolButton(self.groupBox_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_browse_work.sizePolicy().hasHeightForWidth())
        self.toolButton_browse_work.setSizePolicy(sizePolicy)
        self.toolButton_browse_work.setMaximumSize(QtCore.QSize(22, 22))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/menu_icons/folder-open-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_browse_work.setIcon(icon4)
        self.toolButton_browse_work.setObjectName("toolButton_browse_work")
        self.horizontalLayout_6.addWidget(self.toolButton_browse_work)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.checkBox_use_smooth_zoom = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_use_smooth_zoom.setObjectName("checkBox_use_smooth_zoom")
        self.gridLayout.addWidget(self.checkBox_use_smooth_zoom, 7, 0, 1, 1)
        self.checkBox_use_curved_links = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_use_curved_links.setObjectName("checkBox_use_curved_links")
        self.gridLayout.addWidget(self.checkBox_use_curved_links)
        self.label_7 = QtWidgets.QLabel(self.groupBox_general)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_bg_grid = QtWidgets.QRadioButton(self.groupBox_general)
        self.radioButton_bg_grid.setObjectName("radioButton_bg_grid")
        self.horizontalLayout_4.addWidget(self.radioButton_bg_grid)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.radioButton_bg_solid = QtWidgets.QRadioButton(self.groupBox_general)
        self.radioButton_bg_solid.setChecked(True)
        self.radioButton_bg_solid.setObjectName("radioButton_bg_solid")
        self.horizontalLayout_4.addWidget(self.radioButton_bg_solid)
        self.toolButton_bg_color = QtWidgets.QToolButton(self.groupBox_general)
        self.toolButton_bg_color.setMaximumSize(QtCore.QSize(22, 22))
        self.toolButton_bg_color.setIconSize(QtCore.QSize(16, 16))
        self.toolButton_bg_color.setObjectName("toolButton_bg_color")
        self.horizontalLayout_4.addWidget(self.toolButton_bg_color)
        self.gridLayout.addLayout(self.horizontalLayout_4, 10, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_general)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 11, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_general)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_general)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalSlider_data_flow_animation_duration = QtWidgets.QSlider(self.groupBox_general)
        self.horizontalSlider_data_flow_animation_duration.setStyleSheet("")
        self.horizontalSlider_data_flow_animation_duration.setMinimum(1)
        self.horizontalSlider_data_flow_animation_duration.setMaximum(250)
        self.horizontalSlider_data_flow_animation_duration.setSingleStep(10)
        self.horizontalSlider_data_flow_animation_duration.setPageStep(50)
        self.horizontalSlider_data_flow_animation_duration.setSliderPosition(100)
        self.horizontalSlider_data_flow_animation_duration.setTracking(False)
        self.horizontalSlider_data_flow_animation_duration.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_data_flow_animation_duration.setInvertedAppearance(True)
        self.horizontalSlider_data_flow_animation_duration.setInvertedControls(False)
        self.horizontalSlider_data_flow_animation_duration.setObjectName("horizontalSlider_data_flow_animation_duration")
        self.verticalLayout_3.addWidget(self.horizontalSlider_data_flow_animation_duration)
        self.gridLayout.addLayout(self.verticalLayout_3, 12, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 13, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_general)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.General)
        self.Project = QtWidgets.QWidget()
        self.Project.setObjectName("Project")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Project)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_project = QtWidgets.QGroupBox(self.Project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_project.sizePolicy().hasHeightForWidth())
        self.groupBox_project.setSizePolicy(sizePolicy)
        self.groupBox_project.setMinimumSize(QtCore.QSize(250, 150))
        self.groupBox_project.setObjectName("groupBox_project")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_project)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_project)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_project_name = QtWidgets.QLineEdit(self.groupBox_project)
        self.lineEdit_project_name.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_project_name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_project_name.setCursor(QtCore.Qt.IBeamCursor)
        self.lineEdit_project_name.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_project_name.setReadOnly(False)
        self.lineEdit_project_name.setClearButtonEnabled(False)
        self.lineEdit_project_name.setObjectName("lineEdit_project_name")
        self.verticalLayout_2.addWidget(self.lineEdit_project_name)
        self.label_3 = QtWidgets.QLabel(self.groupBox_project)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.textEdit_project_description = QtWidgets.QTextEdit(self.groupBox_project)
        self.textEdit_project_description.setProperty("cursor", QtCore.Qt.IBeamCursor)
        self.textEdit_project_description.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_project_description.setStyleSheet(":focus {border: 1px solid black;}")
        self.textEdit_project_description.setTabChangesFocus(True)
        self.textEdit_project_description.setReadOnly(False)
        self.textEdit_project_description.setAcceptRichText(False)
        self.textEdit_project_description.setPlaceholderText("")
        self.textEdit_project_description.setObjectName("textEdit_project_description")
        self.verticalLayout_2.addWidget(self.textEdit_project_description)
        self.verticalLayout_10.addWidget(self.groupBox_project)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.Project)
        self.ExternalTools = QtWidgets.QWidget()
        self.ExternalTools.setObjectName("ExternalTools")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ExternalTools)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_gams = QtWidgets.QGroupBox(self.ExternalTools)
        self.groupBox_gams.setObjectName("groupBox_gams")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_gams)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_gams)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEdit_gams_path = QtWidgets.QLineEdit(self.groupBox_gams)
        self.lineEdit_gams_path.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_gams_path.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_gams_path.setClearButtonEnabled(True)
        self.lineEdit_gams_path.setObjectName("lineEdit_gams_path")
        self.gridLayout_4.addWidget(self.lineEdit_gams_path, 2, 0, 1, 1)
        self.toolButton_browse_gams = QtWidgets.QToolButton(self.groupBox_gams)
        self.toolButton_browse_gams.setMaximumSize(QtCore.QSize(22, 22))
        self.toolButton_browse_gams.setIcon(icon4)
        self.toolButton_browse_gams.setObjectName("toolButton_browse_gams")
        self.gridLayout_4.addWidget(self.toolButton_browse_gams, 2, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_gams)
        self.groupBox_julia = QtWidgets.QGroupBox(self.ExternalTools)
        self.groupBox_julia.setObjectName("groupBox_julia")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_julia)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.toolButton_browse_julia_project = QtWidgets.QToolButton(self.groupBox_julia)
        self.toolButton_browse_julia_project.setMaximumSize(QtCore.QSize(22, 22))
        self.toolButton_browse_julia_project.setIcon(icon4)
        self.toolButton_browse_julia_project.setObjectName("toolButton_browse_julia_project")
        self.gridLayout_5.addWidget(self.toolButton_browse_julia_project, 4, 1, 1, 1)
        self.lineEdit_julia_project_path = QtWidgets.QLineEdit(self.groupBox_julia)
        self.lineEdit_julia_project_path.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_julia_project_path.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_julia_project_path.setText("")
        self.lineEdit_julia_project_path.setClearButtonEnabled(True)
        self.lineEdit_julia_project_path.setObjectName("lineEdit_julia_project_path")
        self.gridLayout_5.addWidget(self.lineEdit_julia_project_path, 4, 0, 1, 1)
        self.toolButton_browse_julia = QtWidgets.QToolButton(self.groupBox_julia)
        self.toolButton_browse_julia.setMaximumSize(QtCore.QSize(22, 22))
        self.toolButton_browse_julia.setIcon(icon4)
        self.toolButton_browse_julia.setObjectName("toolButton_browse_julia")
        self.gridLayout_5.addWidget(self.toolButton_browse_julia, 3, 1, 1, 1)
        self.lineEdit_julia_path = QtWidgets.QLineEdit(self.groupBox_julia)
        self.lineEdit_julia_path.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_julia_path.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_julia_path.setClearButtonEnabled(True)
        self.lineEdit_julia_path.setObjectName("lineEdit_julia_path")
        self.gridLayout_5.addWidget(self.lineEdit_julia_path, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_julia)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.checkBox_use_embedded_julia = QtWidgets.QCheckBox(self.groupBox_julia)
        self.checkBox_use_embedded_julia.setObjectName("checkBox_use_embedded_julia")
        self.gridLayout_5.addWidget(self.checkBox_use_embedded_julia, 6, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_julia)
        self.groupBox_python = QtWidgets.QGroupBox(self.ExternalTools)
        self.groupBox_python.setMinimumSize(QtCore.QSize(0, 95))
        self.groupBox_python.setObjectName("groupBox_python")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_python)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_python)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.lineEdit_python_path = QtWidgets.QLineEdit(self.groupBox_python)
        self.lineEdit_python_path.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_python_path.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_python_path.setClearButtonEnabled(True)
        self.lineEdit_python_path.setObjectName("lineEdit_python_path")
        self.gridLayout_6.addWidget(self.lineEdit_python_path, 1, 0, 1, 1)
        self.checkBox_use_embedded_python = QtWidgets.QCheckBox(self.groupBox_python)
        self.checkBox_use_embedded_python.setObjectName("checkBox_use_embedded_python")
        self.gridLayout_6.addWidget(self.checkBox_use_embedded_python, 2, 0, 1, 1)
        self.toolButton_browse_python = QtWidgets.QToolButton(self.groupBox_python)
        self.toolButton_browse_python.setMaximumSize(QtCore.QSize(22, 22))
        self.toolButton_browse_python.setIcon(icon4)
        self.toolButton_browse_python.setObjectName("toolButton_browse_python")
        self.gridLayout_6.addWidget(self.toolButton_browse_python, 1, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_python)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.stackedWidget.addWidget(self.ExternalTools)
        self.Views = QtWidgets.QWidget()
        self.Views.setObjectName("Views")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Views)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_data_store = QtWidgets.QGroupBox(self.Views)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_data_store.sizePolicy().hasHeightForWidth())
        self.groupBox_data_store.setSizePolicy(sizePolicy)
        self.groupBox_data_store.setObjectName("groupBox_data_store")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_data_store)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_commit_at_exit = QtWidgets.QCheckBox(self.groupBox_data_store)
        self.checkBox_commit_at_exit.setTristate(True)
        self.checkBox_commit_at_exit.setObjectName("checkBox_commit_at_exit")
        self.verticalLayout_4.addWidget(self.checkBox_commit_at_exit)
        self.checkBox_object_tree_sticky_selection = QtWidgets.QCheckBox(self.groupBox_data_store)
        self.checkBox_object_tree_sticky_selection.setObjectName("checkBox_object_tree_sticky_selection")
        self.verticalLayout_4.addWidget(self.checkBox_object_tree_sticky_selection)
        self.verticalLayout_9.addWidget(self.groupBox_data_store)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.Views)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, 18)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.pushButton_ok = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_ok.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_ok.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.pushButton_cancel = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout)

        self.retranslateUi(SettingsForm)
        self.listWidget.setCurrentRow(-1)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("currentRowChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)
        SettingsForm.setTabOrder(self.listWidget, self.checkBox_open_previous_project)
        SettingsForm.setTabOrder(self.checkBox_open_previous_project, self.checkBox_exit_prompt)
        SettingsForm.setTabOrder(self.checkBox_exit_prompt, self.checkBox_save_at_exit)
        SettingsForm.setTabOrder(self.checkBox_save_at_exit, self.checkBox_datetime)
        SettingsForm.setTabOrder(self.checkBox_datetime, self.checkBox_delete_data)
        SettingsForm.setTabOrder(self.checkBox_delete_data, self.lineEdit_work_dir)
        SettingsForm.setTabOrder(self.lineEdit_work_dir, self.toolButton_browse_work)
        SettingsForm.setTabOrder(self.toolButton_browse_work, self.checkBox_use_smooth_zoom)
        SettingsForm.setTabOrder(self.checkBox_use_smooth_zoom, self.checkBox_use_curved_links)
        SettingsForm.setTabOrder(self.checkBox_use_curved_links, self.radioButton_bg_grid)
        SettingsForm.setTabOrder(self.radioButton_bg_grid, self.radioButton_bg_solid)
        SettingsForm.setTabOrder(self.radioButton_bg_solid, self.toolButton_bg_color)
        SettingsForm.setTabOrder(self.toolButton_bg_color, self.horizontalSlider_data_flow_animation_duration)
        SettingsForm.setTabOrder(self.horizontalSlider_data_flow_animation_duration, self.lineEdit_project_name)
        SettingsForm.setTabOrder(self.lineEdit_project_name, self.textEdit_project_description)
        SettingsForm.setTabOrder(self.textEdit_project_description, self.lineEdit_gams_path)
        SettingsForm.setTabOrder(self.lineEdit_gams_path, self.toolButton_browse_gams)
        SettingsForm.setTabOrder(self.toolButton_browse_gams, self.lineEdit_julia_path)
        SettingsForm.setTabOrder(self.lineEdit_julia_path, self.toolButton_browse_julia)
        SettingsForm.setTabOrder(self.toolButton_browse_julia, self.lineEdit_julia_project_path)
        SettingsForm.setTabOrder(self.lineEdit_julia_project_path, self.toolButton_browse_julia_project)
        SettingsForm.setTabOrder(self.toolButton_browse_julia_project, self.checkBox_use_embedded_julia)
        SettingsForm.setTabOrder(self.checkBox_use_embedded_julia, self.lineEdit_python_path)
        SettingsForm.setTabOrder(self.lineEdit_python_path, self.toolButton_browse_python)
        SettingsForm.setTabOrder(self.toolButton_browse_python, self.checkBox_use_embedded_python)
        SettingsForm.setTabOrder(self.checkBox_use_embedded_python, self.checkBox_commit_at_exit)
        SettingsForm.setTabOrder(self.checkBox_commit_at_exit, self.checkBox_object_tree_sticky_selection)
        SettingsForm.setTabOrder(self.checkBox_object_tree_sticky_selection, self.pushButton_ok)
        SettingsForm.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, SettingsForm):
        SettingsForm.setWindowTitle(QtWidgets.QApplication.translate("SettingsForm", "Settings", None, -1))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtWidgets.QApplication.translate("SettingsForm", "General", None, -1))
        self.listWidget.item(1).setText(QtWidgets.QApplication.translate("SettingsForm", "Project", None, -1))
        self.listWidget.item(2).setText(QtWidgets.QApplication.translate("SettingsForm", "Tools", None, -1))
        self.listWidget.item(3).setText(QtWidgets.QApplication.translate("SettingsForm", "View", None, -1))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_general.setTitle(QtWidgets.QApplication.translate("SettingsForm", "General", None, -1))
        self.checkBox_open_previous_project.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>If checked, Application opens the project at startup that was open the last time the application was exited</p></body></html>", None, -1))
        self.checkBox_open_previous_project.setText(QtWidgets.QApplication.translate("SettingsForm", "Open previous project at startup", None, -1))
        self.checkBox_exit_prompt.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>If checked, confirm exit prompt is shown. If unchecked, application exits without prompt.</p></body></html>", None, -1))
        self.checkBox_exit_prompt.setText(QtWidgets.QApplication.translate("SettingsForm", "Show confirm exit prompt", None, -1))
        self.checkBox_save_at_exit.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Unchecked: Does not save project and does not show message box</p><p>Partially checked: Shows message box (default)</p><p>Checked: Saves project and does not show message box</p><p><br/></p></body></html>", None, -1))
        self.checkBox_save_at_exit.setText(QtWidgets.QApplication.translate("SettingsForm", "Save project at exit", None, -1))
        self.checkBox_datetime.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>If checked, date and time string is appended into Event Log messages</p></body></html>", None, -1))
        self.checkBox_datetime.setText(QtWidgets.QApplication.translate("SettingsForm", "Show date and time in Event Log messages", None, -1))
        self.checkBox_delete_data.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Check this box to delete project item\'s data when a project item is removed from project. This means, that the project item directory and its contens will be deleted from your HD.</p></body></html>", None, -1))
        self.checkBox_delete_data.setText(QtWidgets.QApplication.translate("SettingsForm", "Delete data when project item is removed from project", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SettingsForm", "Work directory", None, -1))
        self.lineEdit_work_dir.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Work directory location. Leave empty to use default (\\work).</p></body></html>", None, -1))
        self.lineEdit_work_dir.setPlaceholderText(QtWidgets.QApplication.translate("SettingsForm", "Using default directory", None, -1))
        self.toolButton_browse_work.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Pick Work directory with file browser</p></body></html>", None, -1))
        self.checkBox_use_smooth_zoom.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Controls whether smooth or discete zoom is used in Design and Graph Views.</p></body></html>", None, -1))
        self.checkBox_use_smooth_zoom.setText(QtWidgets.QApplication.translate("SettingsForm", "Smooth zoom", None, -1))
        self.checkBox_use_curved_links.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Controls whether smooth or straight connectors are used in Design View.</p></body></html>", None, -1))
        self.checkBox_use_curved_links.setText(QtWidgets.QApplication.translate("SettingsForm", "Curved links", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("SettingsForm", "Design View background", None, -1))
        self.radioButton_bg_grid.setText(QtWidgets.QApplication.translate("SettingsForm", "Grid", None, -1))
        self.radioButton_bg_solid.setText(QtWidgets.QApplication.translate("SettingsForm", "Solid", None, -1))
        self.toolButton_bg_color.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Pick solid background color</p></body></html>", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("SettingsForm", "Data flow animation speed", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("SettingsForm", "Slow", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("SettingsForm", "Fast", None, -1))
        self.groupBox_project.setTitle(QtWidgets.QApplication.translate("SettingsForm", "Project", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("SettingsForm", "Name", None, -1))
        self.lineEdit_project_name.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Change project name by typing a new name here</p></body></html>", None, -1))
        self.lineEdit_project_name.setPlaceholderText(QtWidgets.QApplication.translate("SettingsForm", "No project open", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("SettingsForm", "Description", None, -1))
        self.textEdit_project_description.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Project description</p></body></html>", None, -1))
        self.textEdit_project_description.setHtml(QtWidgets.QApplication.translate("SettingsForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, -1))
        self.groupBox_gams.setTitle(QtWidgets.QApplication.translate("SettingsForm", "GAMS", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("SettingsForm", "GAMS executable", None, -1))
        self.lineEdit_gams_path.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Path to GAMS executable for Tool and GAMS Python bindings. Leave blank to use system\'s default</p></body></html>", None, -1))
        self.lineEdit_gams_path.setPlaceholderText(QtWidgets.QApplication.translate("SettingsForm", "Using system\'s default GAMS", None, -1))
        self.toolButton_browse_gams.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Pick GAMS executable with file browser (eg. gams.exe on Windows)</p></body></html>", None, -1))
        self.groupBox_julia.setTitle(QtWidgets.QApplication.translate("SettingsForm", "Julia", None, -1))
        self.toolButton_browse_julia_project.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Pick Julia project with file browser</p></body></html>", None, -1))
        self.toolButton_browse_julia_project.setText(QtWidgets.QApplication.translate("SettingsForm", "...", None, -1))
        self.lineEdit_julia_project_path.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Julia project</p></body></html>", None, -1))
        self.lineEdit_julia_project_path.setPlaceholderText(QtWidgets.QApplication.translate("SettingsForm", "Using Julia home project", None, -1))
        self.toolButton_browse_julia.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Pick Julia executable with file browser</p></body></html>", None, -1))
        self.lineEdit_julia_path.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Julia executable. Leave blank to use Julia defined in your system path.</p></body></html>", None, -1))
        self.lineEdit_julia_path.setPlaceholderText(QtWidgets.QApplication.translate("SettingsForm", "Using Julia executable in system path", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("SettingsForm", "Julia executable", None, -1))
        self.checkBox_use_embedded_julia.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>If checked, Julia Tools and scripts will be executed in the embedded Julia Console (Shell). If unchecked, Julia Tools and scripts will be executed in a terminal as an individual process. I.e. the same as running `julia script.jl` in terminal.</p></body></html>", None, -1))
        self.checkBox_use_embedded_julia.setText(QtWidgets.QApplication.translate("SettingsForm", "Use embedded Julia Console", None, -1))
        self.groupBox_python.setTitle(QtWidgets.QApplication.translate("SettingsForm", "Python", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("SettingsForm", "Python interpreter", None, -1))
        self.lineEdit_python_path.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Python interpreter. Leave blank to use Python defined in your system path.</p></body></html>", None, -1))
        self.lineEdit_python_path.setPlaceholderText(QtWidgets.QApplication.translate("SettingsForm", "Using Python interpreter in system path", None, -1))
        self.checkBox_use_embedded_python.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>If checked, Python Tools and scripts will be executed in the embedded Python Console (Shell). If unchecked, Python Tools and scripts will be executed in a terminal as an individual process. I.e. the same as running `python script.py` in terminal.</p></body></html>", None, -1))
        self.checkBox_use_embedded_python.setText(QtWidgets.QApplication.translate("SettingsForm", "Use embedded Python Console", None, -1))
        self.toolButton_browse_python.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Pick Python interpreter with file browser</p></body></html>", None, -1))
        self.groupBox_data_store.setTitle(QtWidgets.QApplication.translate("SettingsForm", "Data store view", None, -1))
        self.checkBox_commit_at_exit.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Unchecked: Does not commit session and does not show message box</p><p>Partially checked: Shows message box (default)</p><p>Checked: Commits session and does not show message box</p><p><br/></p></body></html>", None, -1))
        self.checkBox_commit_at_exit.setText(QtWidgets.QApplication.translate("SettingsForm", "Commit session when view is closed", None, -1))
        self.checkBox_object_tree_sticky_selection.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Controls how selecting items in Graph View\'s Object tree <span style=\" font-weight:600;\">using the left mouse button</span> works. </p><p>When unchecked [default], Single selection is enabled. Pressing the Ctrl-button down enables multiple selection.</p><p>When checked, Multiple selection is enabled. Pressing the Ctrl-button down enables single selection.</p></body></html>", None, -1))
        self.checkBox_object_tree_sticky_selection.setText(QtWidgets.QApplication.translate("SettingsForm", "Sticky selection in object tree", None, -1))
        self.pushButton_ok.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Saves changes and closes the window</p></body></html>", None, -1))
        self.pushButton_ok.setText(QtWidgets.QApplication.translate("SettingsForm", "Ok", None, -1))
        self.pushButton_cancel.setToolTip(QtWidgets.QApplication.translate("SettingsForm", "<html><head/><body><p>Closes the window without saving changes</p></body></html>", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("SettingsForm", "Cancel", None, -1))

from spinetoolbox import resources_icons_rc
