# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../spinetoolbox/ui/Spine_data_explorer.ui'
#
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(782, 559)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_object_tree = QtWidgets.QLabel(self.layoutWidget)
        self.label_object_tree.setObjectName("label_object_tree")
        self.verticalLayout_3.addWidget(self.label_object_tree)
        self.treeView_object = QtWidgets.QTreeView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_object.sizePolicy().hasHeightForWidth())
        self.treeView_object.setSizePolicy(sizePolicy)
        self.treeView_object.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView_object.setObjectName("treeView_object")
        self.verticalLayout_3.addWidget(self.treeView_object)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_object_parameter = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_object_parameter.sizePolicy().hasHeightForWidth())
        self.label_object_parameter.setSizePolicy(sizePolicy)
        self.label_object_parameter.setObjectName("label_object_parameter")
        self.verticalLayout_2.addWidget(self.label_object_parameter)
        self.tableView_object_parameter = QtWidgets.QTableView(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_object_parameter.sizePolicy().hasHeightForWidth())
        self.tableView_object_parameter.setSizePolicy(sizePolicy)
        self.tableView_object_parameter.setObjectName("tableView_object_parameter")
        self.verticalLayout_2.addWidget(self.tableView_object_parameter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton_add_object_parameter = QtWidgets.QToolButton(self.layoutWidget1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_add_object_parameter.setIcon(icon)
        self.toolButton_add_object_parameter.setObjectName("toolButton_add_object_parameter")
        self.horizontalLayout_3.addWidget(self.toolButton_add_object_parameter)
        self.toolButton_remove_object_parameter = QtWidgets.QToolButton(self.layoutWidget1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_remove_object_parameter.setIcon(icon1)
        self.toolButton_remove_object_parameter.setObjectName("toolButton_remove_object_parameter")
        self.horizontalLayout_3.addWidget(self.toolButton_remove_object_parameter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_parameter_as_parent = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_parameter_as_parent.sizePolicy().hasHeightForWidth())
        self.label_parameter_as_parent.setSizePolicy(sizePolicy)
        self.label_parameter_as_parent.setObjectName("label_parameter_as_parent")
        self.verticalLayout.addWidget(self.label_parameter_as_parent)
        self.tableView_parameter_as_parent = QtWidgets.QTableView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_parameter_as_parent.sizePolicy().hasHeightForWidth())
        self.tableView_parameter_as_parent.setSizePolicy(sizePolicy)
        self.tableView_parameter_as_parent.setObjectName("tableView_parameter_as_parent")
        self.verticalLayout.addWidget(self.tableView_parameter_as_parent)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_add_parameter_as_parent_2 = QtWidgets.QToolButton(self.widget)
        self.toolButton_add_parameter_as_parent_2.setIcon(icon)
        self.toolButton_add_parameter_as_parent_2.setObjectName("toolButton_add_parameter_as_parent_2")
        self.horizontalLayout_4.addWidget(self.toolButton_add_parameter_as_parent_2)
        self.toolButton_remove_parameter_as_parent_2 = QtWidgets.QToolButton(self.widget)
        self.toolButton_remove_parameter_as_parent_2.setIcon(icon1)
        self.toolButton_remove_parameter_as_parent_2.setObjectName("toolButton_remove_parameter_as_parent_2")
        self.horizontalLayout_4.addWidget(self.toolButton_remove_parameter_as_parent_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_parameter_as_child = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_parameter_as_child.sizePolicy().hasHeightForWidth())
        self.label_parameter_as_child.setSizePolicy(sizePolicy)
        self.label_parameter_as_child.setObjectName("label_parameter_as_child")
        self.verticalLayout_4.addWidget(self.label_parameter_as_child)
        self.tableView_parameter_as_child = QtWidgets.QTableView(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_parameter_as_child.sizePolicy().hasHeightForWidth())
        self.tableView_parameter_as_child.setSizePolicy(sizePolicy)
        self.tableView_parameter_as_child.setObjectName("tableView_parameter_as_child")
        self.verticalLayout_4.addWidget(self.tableView_parameter_as_child)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton_add_parameter_as_child = QtWidgets.QToolButton(self.widget1)
        self.toolButton_add_parameter_as_child.setIcon(icon)
        self.toolButton_add_parameter_as_child.setObjectName("toolButton_add_parameter_as_child")
        self.horizontalLayout_5.addWidget(self.toolButton_add_parameter_as_child)
        self.toolButton_remove_parameter_as_child = QtWidgets.QToolButton(self.widget1)
        self.toolButton_remove_parameter_as_child.setIcon(icon1)
        self.toolButton_remove_parameter_as_child.setObjectName("toolButton_remove_parameter_as_child")
        self.horizontalLayout_5.addWidget(self.toolButton_remove_parameter_as_child)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.splitter_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_commit = QtWidgets.QPushButton(Form)
        self.pushButton_commit.setObjectName("pushButton_commit")
        self.horizontalLayout_2.addWidget(self.pushButton_commit)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_statusbar_placeholder = QtWidgets.QHBoxLayout()
        self.horizontalLayout_statusbar_placeholder.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_statusbar_placeholder.setObjectName("horizontalLayout_statusbar_placeholder")
        self.widget_invisible_dummy = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_invisible_dummy.sizePolicy().hasHeightForWidth())
        self.widget_invisible_dummy.setSizePolicy(sizePolicy)
        self.widget_invisible_dummy.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_invisible_dummy.setMaximumSize(QtCore.QSize(0, 20))
        self.widget_invisible_dummy.setObjectName("widget_invisible_dummy")
        self.horizontalLayout_statusbar_placeholder.addWidget(self.widget_invisible_dummy)
        self.verticalLayout_7.addLayout(self.horizontalLayout_statusbar_placeholder)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Spine Data Explorer", None, -1))
        self.label_object_tree.setText(QtWidgets.QApplication.translate("Form", "<b>Object tree</b>", None, -1))
        self.label_object_parameter.setText(QtWidgets.QApplication.translate("Form", "<b>Object parameter</b>", None, -1))
        self.toolButton_add_object_parameter.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_remove_object_parameter.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.label_parameter_as_parent.setText(QtWidgets.QApplication.translate("Form", "<b>Relationship parameter (as parent)</b>", None, -1))
        self.toolButton_add_parameter_as_parent_2.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_remove_parameter_as_parent_2.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.label_parameter_as_child.setText(QtWidgets.QApplication.translate("Form", "<b>Relationship parameter (as child)</b>", None, -1))
        self.toolButton_add_parameter_as_child.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_remove_parameter_as_child.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Commit message:", None, -1))
        self.pushButton_commit.setText(QtWidgets.QApplication.translate("Form", "Commit", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("Form", "Cancel", None, -1))

import resources_icons_rc
