######################################################################################################################
# Copyright (C) 2017 - 2018 Spine project consortium
# This file is part of Spine Toolbox.
# Spine Toolbox is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
# Public License for more details. You should have received a copy of the GNU Lesser General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
######################################################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../spinetoolbox/ui/spine_datapackage_form.ui',
# licensing of '../spinetoolbox/ui/spine_datapackage_form.ui' applies.
#
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget_resources = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_resources.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget_resources.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_resources.setObjectName("tabWidget_resources")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView_resources = QtWidgets.QTreeView(self.tab)
        self.treeView_resources.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.treeView_resources.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeView_resources.setObjectName("treeView_resources")
        self.verticalLayout_2.addWidget(self.treeView_resources)
        self.tabWidget_resources.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.tabWidget_resources.addTab(self.tab_2, "")
        self.tabWidget_data_schema = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_data_schema.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget_data_schema.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_data_schema.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_data_schema.setTabsClosable(False)
        self.tabWidget_data_schema.setObjectName("tabWidget_data_schema")
        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_data)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView_resource_data = CopyPasteTableView(self.tab_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_resource_data.sizePolicy().hasHeightForWidth())
        self.tableView_resource_data.setSizePolicy(sizePolicy)
        self.tableView_resource_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_resource_data.setTabKeyNavigation(False)
        self.tableView_resource_data.setObjectName("tableView_resource_data")
        self.tableView_resource_data.horizontalHeader().setVisible(True)
        self.tableView_resource_data.horizontalHeader().setHighlightSections(False)
        self.tableView_resource_data.verticalHeader().setVisible(False)
        self.tableView_resource_data.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.tableView_resource_data)
        self.tabWidget_data_schema.addTab(self.tab_data, "")
        self.tab_schema = QtWidgets.QWidget()
        self.tab_schema.setObjectName("tab_schema")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_schema)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_schema)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableView_fields = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_fields.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_fields.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_fields.setShowGrid(True)
        self.tableView_fields.setObjectName("tableView_fields")
        self.tableView_fields.horizontalHeader().setHighlightSections(False)
        self.tableView_fields.horizontalHeader().setSortIndicatorShown(False)
        self.tableView_fields.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tableView_fields)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_schema)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_foreign_keys = QtWidgets.QTableView(self.groupBox)
        self.tableView_foreign_keys.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_foreign_keys.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_foreign_keys.setShowGrid(True)
        self.tableView_foreign_keys.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView_foreign_keys.setObjectName("tableView_foreign_keys")
        self.tableView_foreign_keys.horizontalHeader().setHighlightSections(False)
        self.tableView_foreign_keys.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tableView_foreign_keys)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget_data_schema.addTab(self.tab_schema, "")
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 28))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setToolTipsVisible(True)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_datapackage = QtWidgets.QAction(MainWindow)
        self.actionSave_datapackage.setObjectName("actionSave_datapackage")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.actionRemove_foreign_keys = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_foreign_keys.setIcon(icon1)
        self.actionRemove_foreign_keys.setObjectName("actionRemove_foreign_keys")
        self.actionLoad_datapackage = QtWidgets.QAction(MainWindow)
        self.actionLoad_datapackage.setObjectName("actionLoad_datapackage")
        self.actionExport_to_spine = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Spine_db_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_to_spine.setIcon(icon2)
        self.actionExport_to_spine.setObjectName("actionExport_to_spine")
        self.menuFile.addAction(self.actionLoad_datapackage)
        self.menuFile.addAction(self.actionSave_datapackage)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_to_spine)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_resources.setCurrentIndex(0)
        self.tabWidget_data_schema.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Spine datapackage editor", None, -1))
        self.tabWidget_resources.setTabText(self.tabWidget_resources.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Resources", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Not in use at the moment", None, -1))
        self.tabWidget_resources.setTabText(self.tabWidget_resources.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Metadata", None, -1))
        self.tabWidget_data_schema.setTabText(self.tabWidget_data_schema.indexOf(self.tab_data), QtWidgets.QApplication.translate("MainWindow", "Data", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Fields", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Foreign keys", None, -1))
        self.tabWidget_data_schema.setTabText(self.tabWidget_data_schema.indexOf(self.tab_schema), QtWidgets.QApplication.translate("MainWindow", "Schema", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionSave_datapackage.setText(QtWidgets.QApplication.translate("MainWindow", "Save \"datapackage.json\"", None, -1))
        self.actionSave_datapackage.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Save as \'datapackage.json\'", None, -1))
        self.actionSave_datapackage.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))
        self.actionClose.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None, -1))
        self.actionRemove_foreign_keys.setText(QtWidgets.QApplication.translate("MainWindow", "Remove foreign keys", None, -1))
        self.actionRemove_foreign_keys.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Remove selected foreign keys.", None, -1))
        self.actionLoad_datapackage.setText(QtWidgets.QApplication.translate("MainWindow", "Load datapackage", None, -1))
        self.actionLoad_datapackage.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+L", None, -1))
        self.actionExport_to_spine.setText(QtWidgets.QApplication.translate("MainWindow", "Export to Spine format", None, -1))
        self.actionExport_to_spine.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))

from widgets.custom_qtableview import CopyPasteTableView
import resources_icons_rc
