# -*- coding: utf-8 -*-
######################################################################################################################
# Copyright (C) 2017-2020 Spine project consortium
# This file is part of Spine Toolbox.
# Spine Toolbox is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
# Public License for more details. You should have received a copy of the GNU Lesser General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
######################################################################################################################

################################################################################
## Form generated from reading UI file 'spine_datapackage_form.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

from spinetoolbox.widgets.custom_qtableview import CopyPasteTableView

from spinetoolbox import resources_icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1088, 824)
        self.actionSave_datapackage = QAction(MainWindow)
        self.actionSave_datapackage.setObjectName(u"actionSave_datapackage")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon = QIcon()
        icon.addFile(u":/icons/close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon)
        self.actionRemove_foreign_keys = QAction(MainWindow)
        self.actionRemove_foreign_keys.setObjectName(u"actionRemove_foreign_keys")
        icon1 = QIcon()
        icon1.addFile(u":/icons/minus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRemove_foreign_keys.setIcon(icon1)
        self.actionInfer_datapackage = QAction(MainWindow)
        self.actionInfer_datapackage.setObjectName(u"actionInfer_datapackage")
        self.actionExport_to_spine = QAction(MainWindow)
        self.actionExport_to_spine.setObjectName(u"actionExport_to_spine")
        icon2 = QIcon()
        icon2.addFile(u":/icons/Spine_db_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExport_to_spine.setIcon(icon2)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon3 = QIcon()
        icon3.addFile(u":/icons/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon3)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon4 = QIcon()
        icon4.addFile(u":/icons/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon4)
        self.actionxx = QAction(MainWindow)
        self.actionxx.setObjectName(u"actionxx")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.frame = QFrame(self.splitter)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(9, 0, 9, 9)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.label)

        self.tableView_resources = CopyPasteTableView(self.frame)
        self.tableView_resources.setObjectName(u"tableView_resources")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tableView_resources.sizePolicy().hasHeightForWidth())
        self.tableView_resources.setSizePolicy(sizePolicy1)
        self.tableView_resources.setLayoutDirection(Qt.LeftToRight)
        self.tableView_resources.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.tableView_resources.setShowGrid(False)
        self.tableView_resources.horizontalHeader().setHighlightSections(False)
        self.tableView_resources.verticalHeader().setVisible(False)

        self.verticalLayout.addWidget(self.tableView_resources)

        self.splitter.addWidget(self.frame)
        self.frame_2 = QFrame(self.splitter)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(3)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy2)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(9, 0, 9, 9)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(2)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy3)

        self.verticalLayout_3.addWidget(self.label_2)

        self.tableView_resource_data = CopyPasteTableView(self.frame_2)
        self.tableView_resource_data.setObjectName(u"tableView_resource_data")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy4.setHorizontalStretch(2)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.tableView_resource_data.sizePolicy().hasHeightForWidth())
        self.tableView_resource_data.setSizePolicy(sizePolicy4)
        self.tableView_resource_data.setLayoutDirection(Qt.LeftToRight)
        self.tableView_resource_data.setTabKeyNavigation(False)
        self.tableView_resource_data.horizontalHeader().setVisible(True)
        self.tableView_resource_data.horizontalHeader().setHighlightSections(False)
        self.tableView_resource_data.verticalHeader().setVisible(False)
        self.tableView_resource_data.verticalHeader().setHighlightSections(False)

        self.verticalLayout_3.addWidget(self.tableView_resource_data)

        self.splitter.addWidget(self.frame_2)

        self.verticalLayout_2.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1088, 28))
        self.menubar.setNativeMenuBar(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setToolTipsVisible(True)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuDock_Widgets = QMenu(self.menuView)
        self.menuDock_Widgets.setObjectName(u"menuDock_Widgets")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_fields = QDockWidget(MainWindow)
        self.dockWidget_fields.setObjectName(u"dockWidget_fields")
        self.dockWidget_fields.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.dockWidgetContents_5 = QWidget()
        self.dockWidgetContents_5.setObjectName(u"dockWidgetContents_5")
        self.verticalLayout_8 = QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.tableView_fields = CopyPasteTableView(self.dockWidgetContents_5)
        self.tableView_fields.setObjectName(u"tableView_fields")
        self.tableView_fields.setLayoutDirection(Qt.LeftToRight)
        self.tableView_fields.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.tableView_fields.setShowGrid(True)
        self.tableView_fields.horizontalHeader().setHighlightSections(False)
        self.tableView_fields.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableView_fields.verticalHeader().setVisible(False)

        self.verticalLayout_8.addWidget(self.tableView_fields)

        self.dockWidget_fields.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget_fields)
        self.dockWidget_foreign_keys = QDockWidget(MainWindow)
        self.dockWidget_foreign_keys.setObjectName(u"dockWidget_foreign_keys")
        self.dockWidgetContents_6 = QWidget()
        self.dockWidgetContents_6.setObjectName(u"dockWidgetContents_6")
        self.verticalLayout_9 = QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.tableView_foreign_keys = CopyPasteTableView(self.dockWidgetContents_6)
        self.tableView_foreign_keys.setObjectName(u"tableView_foreign_keys")
        self.tableView_foreign_keys.setLayoutDirection(Qt.LeftToRight)
        self.tableView_foreign_keys.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.tableView_foreign_keys.setShowGrid(True)
        self.tableView_foreign_keys.setGridStyle(Qt.SolidLine)
        self.tableView_foreign_keys.horizontalHeader().setHighlightSections(False)
        self.tableView_foreign_keys.verticalHeader().setVisible(True)

        self.verticalLayout_9.addWidget(self.tableView_foreign_keys)

        self.dockWidget_foreign_keys.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget_foreign_keys)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionInfer_datapackage)
        self.menuFile.addAction(self.actionSave_datapackage)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_to_spine)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuView.addAction(self.menuDock_Widgets.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Spine datapackage editor", None))
        self.actionSave_datapackage.setText(QCoreApplication.translate("MainWindow", u"Save \"datapackage.json\"", None))
#if QT_CONFIG(tooltip)
        self.actionSave_datapackage.setToolTip(QCoreApplication.translate("MainWindow", u"Save as 'datapackage.json'", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave_datapackage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
#if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionRemove_foreign_keys.setText(QCoreApplication.translate("MainWindow", u"Remove foreign keys", None))
#if QT_CONFIG(tooltip)
        self.actionRemove_foreign_keys.setToolTip(QCoreApplication.translate("MainWindow", u"Remove selected foreign keys.", None))
#endif // QT_CONFIG(tooltip)
        self.actionInfer_datapackage.setText(QCoreApplication.translate("MainWindow", u"Infer datapackage", None))
#if QT_CONFIG(tooltip)
        self.actionInfer_datapackage.setToolTip(QCoreApplication.translate("MainWindow", u"(Re)infer datapackage from CSV files in data directory.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionInfer_datapackage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport_to_spine.setText(QCoreApplication.translate("MainWindow", u"Export to Spine format", None))
#if QT_CONFIG(shortcut)
        self.actionExport_to_spine.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionxx.setText(QCoreApplication.translate("MainWindow", u"xx", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Resources", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuDock_Widgets.setTitle(QCoreApplication.translate("MainWindow", u"Dock Widgets", None))
        self.dockWidget_fields.setWindowTitle(QCoreApplication.translate("MainWindow", u"Fields", None))
        self.dockWidget_foreign_keys.setWindowTitle(QCoreApplication.translate("MainWindow", u"Foreign keys", None))
    # retranslateUi

