######################################################################################################################
# Copyright (C) 2017 - 2018 Spine project consortium
# This file is part of Spine Toolbox.
# Spine Toolbox is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
# Public License for more details. You should have received a copy of the GNU Lesser General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
######################################################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../spinetoolbox/ui/tree_view_form.ui',
# licensing of '../spinetoolbox/ui/tree_view_form.ui' applies.
#
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1077, 774)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_tree_parameter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_tree_parameter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_tree_parameter.setObjectName("splitter_tree_parameter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_tree_parameter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_tree = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_tree.setSpacing(0)
        self.verticalLayout_tree.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_tree.setObjectName("verticalLayout_tree")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(3, 1, 0, 2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_object_tree = QtWidgets.QLabel(self.layoutWidget)
        self.label_object_tree.setObjectName("label_object_tree")
        self.horizontalLayout_4.addWidget(self.label_object_tree)
        self.verticalLayout_tree.addLayout(self.horizontalLayout_4)
        self.treeView_object = ObjectTreeView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_object.sizePolicy().hasHeightForWidth())
        self.treeView_object.setSizePolicy(sizePolicy)
        self.treeView_object.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView_object.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeView_object.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView_object.setIconSize(QtCore.QSize(20, 20))
        self.treeView_object.setObjectName("treeView_object")
        self.verticalLayout_tree.addWidget(self.treeView_object)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.splitter_tree_parameter)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_parameter = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_parameter.setSpacing(0)
        self.verticalLayout_parameter.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_parameter.setObjectName("verticalLayout_parameter")
        self.splitter = QtWidgets.QSplitter(self.verticalLayoutWidget_5)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget_object_parameter = QtWidgets.QTabWidget(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_object_parameter.sizePolicy().hasHeightForWidth())
        self.tabWidget_object_parameter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tabWidget_object_parameter.setFont(font)
        self.tabWidget_object_parameter.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabWidget_object_parameter.setAccessibleName("")
        self.tabWidget_object_parameter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_object_parameter.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_object_parameter.setTabBarAutoHide(False)
        self.tabWidget_object_parameter.setObjectName("tabWidget_object_parameter")
        self.tab_object_parameter_value = QtWidgets.QWidget()
        self.tab_object_parameter_value.setObjectName("tab_object_parameter_value")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_object_parameter_value)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_object_parameter_value_json = QtWidgets.QSplitter(self.tab_object_parameter_value)
        self.splitter_object_parameter_value_json.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter_object_parameter_value_json.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_object_parameter_value_json.setObjectName("splitter_object_parameter_value_json")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_object_parameter_value_json)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView_object_parameter_value = AutoFilterCopyPasteTableView(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_object_parameter_value.sizePolicy().hasHeightForWidth())
        self.tableView_object_parameter_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tableView_object_parameter_value.setFont(font)
        self.tableView_object_parameter_value.setMouseTracking(True)
        self.tableView_object_parameter_value.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_object_parameter_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_object_parameter_value.setTabKeyNavigation(False)
        self.tableView_object_parameter_value.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_object_parameter_value.setSortingEnabled(False)
        self.tableView_object_parameter_value.setWordWrap(False)
        self.tableView_object_parameter_value.setObjectName("tableView_object_parameter_value")
        self.tableView_object_parameter_value.horizontalHeader().setHighlightSections(False)
        self.tableView_object_parameter_value.verticalHeader().setVisible(False)
        self.tableView_object_parameter_value.verticalHeader().setHighlightSections(False)
        self.tableView_object_parameter_value.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout.addWidget(self.tableView_object_parameter_value)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_object_parameter_value_json)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.tabWidget_object_parameter_json = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget_object_parameter_json.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget_object_parameter_json.setObjectName("tabWidget_object_parameter_json")
        self.json_obj = QtWidgets.QWidget()
        self.json_obj.setObjectName("json_obj")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.json_obj)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.textEdit_object_parameter_json = QtWidgets.QTextEdit(self.json_obj)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_object_parameter_json.sizePolicy().hasHeightForWidth())
        self.textEdit_object_parameter_json.setSizePolicy(sizePolicy)
        self.textEdit_object_parameter_json.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_object_parameter_json.setTabChangesFocus(True)
        self.textEdit_object_parameter_json.setObjectName("textEdit_object_parameter_json")
        self.verticalLayout_13.addWidget(self.textEdit_object_parameter_json)
        self.tabWidget_object_parameter_json.addTab(self.json_obj, "")
        self.json_arr = QtWidgets.QWidget()
        self.json_arr.setObjectName("json_arr")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.json_arr)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_object_parameter_json_error = QtWidgets.QLabel(self.json_arr)
        self.label_object_parameter_json_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_object_parameter_json_error.setObjectName("label_object_parameter_json_error")
        self.verticalLayout_14.addWidget(self.label_object_parameter_json_error)
        self.tableView_object_parameter_json = CopyPasteTableView(self.json_arr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_object_parameter_json.sizePolicy().hasHeightForWidth())
        self.tableView_object_parameter_json.setSizePolicy(sizePolicy)
        self.tableView_object_parameter_json.setTabKeyNavigation(False)
        self.tableView_object_parameter_json.setObjectName("tableView_object_parameter_json")
        self.tableView_object_parameter_json.horizontalHeader().setVisible(False)
        self.tableView_object_parameter_json.horizontalHeader().setHighlightSections(False)
        self.tableView_object_parameter_json.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_14.addWidget(self.tableView_object_parameter_json)
        self.tabWidget_object_parameter_json.addTab(self.json_arr, "")
        self.verticalLayout_11.addWidget(self.tabWidget_object_parameter_json)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_object_parameter_json_ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_object_parameter_json_ok.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_object_parameter_json_ok.setObjectName("pushButton_object_parameter_json_ok")
        self.horizontalLayout_7.addWidget(self.pushButton_object_parameter_json_ok)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.splitter_object_parameter_value_json)
        self.tabWidget_object_parameter.addTab(self.tab_object_parameter_value, "")
        self.tab_object_parameter_definition = QtWidgets.QWidget()
        self.tab_object_parameter_definition.setObjectName("tab_object_parameter_definition")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_object_parameter_definition)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableView_object_parameter_definition = AutoFilterCopyPasteTableView(self.tab_object_parameter_definition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_object_parameter_definition.sizePolicy().hasHeightForWidth())
        self.tableView_object_parameter_definition.setSizePolicy(sizePolicy)
        self.tableView_object_parameter_definition.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_object_parameter_definition.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_object_parameter_definition.setTabKeyNavigation(False)
        self.tableView_object_parameter_definition.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_object_parameter_definition.setSortingEnabled(False)
        self.tableView_object_parameter_definition.setWordWrap(False)
        self.tableView_object_parameter_definition.setObjectName("tableView_object_parameter_definition")
        self.tableView_object_parameter_definition.horizontalHeader().setHighlightSections(False)
        self.tableView_object_parameter_definition.horizontalHeader().setSortIndicatorShown(False)
        self.tableView_object_parameter_definition.verticalHeader().setVisible(False)
        self.tableView_object_parameter_definition.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_5.addWidget(self.tableView_object_parameter_definition)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.tabWidget_object_parameter.addTab(self.tab_object_parameter_definition, "")
        self.verticalLayout_10.addWidget(self.tabWidget_object_parameter)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidget_relationship_parameter = QtWidgets.QTabWidget(self.verticalLayoutWidget_4)
        self.tabWidget_relationship_parameter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_relationship_parameter.sizePolicy().hasHeightForWidth())
        self.tabWidget_relationship_parameter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tabWidget_relationship_parameter.setFont(font)
        self.tabWidget_relationship_parameter.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabWidget_relationship_parameter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_relationship_parameter.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_relationship_parameter.setUsesScrollButtons(False)
        self.tabWidget_relationship_parameter.setObjectName("tabWidget_relationship_parameter")
        self.tab_relationship_parameter_value = QtWidgets.QWidget()
        self.tab_relationship_parameter_value.setObjectName("tab_relationship_parameter_value")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_relationship_parameter_value)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter_relationship_parameter_value_json = QtWidgets.QSplitter(self.tab_relationship_parameter_value)
        self.splitter_relationship_parameter_value_json.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter_relationship_parameter_value_json.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_relationship_parameter_value_json.setObjectName("splitter_relationship_parameter_value_json")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_relationship_parameter_value_json)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView_relationship_parameter_value = AutoFilterCopyPasteTableView(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_relationship_parameter_value.sizePolicy().hasHeightForWidth())
        self.tableView_relationship_parameter_value.setSizePolicy(sizePolicy)
        self.tableView_relationship_parameter_value.setMouseTracking(True)
        self.tableView_relationship_parameter_value.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_relationship_parameter_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_relationship_parameter_value.setTabKeyNavigation(False)
        self.tableView_relationship_parameter_value.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_relationship_parameter_value.setSortingEnabled(False)
        self.tableView_relationship_parameter_value.setWordWrap(False)
        self.tableView_relationship_parameter_value.setObjectName("tableView_relationship_parameter_value")
        self.tableView_relationship_parameter_value.horizontalHeader().setHighlightSections(False)
        self.tableView_relationship_parameter_value.verticalHeader().setVisible(False)
        self.tableView_relationship_parameter_value.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_2.addWidget(self.tableView_relationship_parameter_value)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_relationship_parameter_value_json)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.tabWidget_relationship_parameter_json = QtWidgets.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget_relationship_parameter_json.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget_relationship_parameter_json.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_relationship_parameter_json.setObjectName("tabWidget_relationship_parameter_json")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.textEdit_relationship_parameter_json = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_relationship_parameter_json.sizePolicy().hasHeightForWidth())
        self.textEdit_relationship_parameter_json.setSizePolicy(sizePolicy)
        self.textEdit_relationship_parameter_json.setTabChangesFocus(True)
        self.textEdit_relationship_parameter_json.setObjectName("textEdit_relationship_parameter_json")
        self.verticalLayout_15.addWidget(self.textEdit_relationship_parameter_json)
        self.tabWidget_relationship_parameter_json.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_relationship_parameter_json_error = QtWidgets.QLabel(self.tab_2)
        self.label_relationship_parameter_json_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_relationship_parameter_json_error.setObjectName("label_relationship_parameter_json_error")
        self.verticalLayout_16.addWidget(self.label_relationship_parameter_json_error)
        self.tableView_relationship_parameter_json = CopyPasteTableView(self.tab_2)
        self.tableView_relationship_parameter_json.setTabKeyNavigation(False)
        self.tableView_relationship_parameter_json.setObjectName("tableView_relationship_parameter_json")
        self.tableView_relationship_parameter_json.horizontalHeader().setVisible(False)
        self.tableView_relationship_parameter_json.horizontalHeader().setHighlightSections(False)
        self.tableView_relationship_parameter_json.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_16.addWidget(self.tableView_relationship_parameter_json)
        self.tabWidget_relationship_parameter_json.addTab(self.tab_2, "")
        self.verticalLayout_12.addWidget(self.tabWidget_relationship_parameter_json)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.pushButton_relationship_parameter_json_ok = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_relationship_parameter_json_ok.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_relationship_parameter_json_ok.setObjectName("pushButton_relationship_parameter_json_ok")
        self.horizontalLayout_8.addWidget(self.pushButton_relationship_parameter_json_ok)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.verticalLayout_9.addWidget(self.splitter_relationship_parameter_value_json)
        self.tabWidget_relationship_parameter.addTab(self.tab_relationship_parameter_value, "")
        self.tab_relationship_parameter_definition = QtWidgets.QWidget()
        self.tab_relationship_parameter_definition.setObjectName("tab_relationship_parameter_definition")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_relationship_parameter_definition)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableView_relationship_parameter_definition = AutoFilterCopyPasteTableView(self.tab_relationship_parameter_definition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_relationship_parameter_definition.sizePolicy().hasHeightForWidth())
        self.tableView_relationship_parameter_definition.setSizePolicy(sizePolicy)
        self.tableView_relationship_parameter_definition.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView_relationship_parameter_definition.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_relationship_parameter_definition.setTabKeyNavigation(False)
        self.tableView_relationship_parameter_definition.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_relationship_parameter_definition.setSortingEnabled(False)
        self.tableView_relationship_parameter_definition.setWordWrap(False)
        self.tableView_relationship_parameter_definition.setObjectName("tableView_relationship_parameter_definition")
        self.tableView_relationship_parameter_definition.horizontalHeader().setHighlightSections(False)
        self.tableView_relationship_parameter_definition.verticalHeader().setVisible(False)
        self.tableView_relationship_parameter_definition.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_3.addWidget(self.tableView_relationship_parameter_definition)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.tabWidget_relationship_parameter.addTab(self.tab_relationship_parameter_definition, "")
        self.verticalLayout_18.addWidget(self.tabWidget_relationship_parameter)
        self.verticalLayout_parameter.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.splitter_tree_parameter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 28))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuSession = QtWidgets.QMenu(self.menubar)
        self.menuSession.setObjectName("menuSession")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuToolbars = QtWidgets.QMenu(self.menuView)
        self.menuToolbars.setObjectName("menuToolbars")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_parameter_enum = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_parameter_enum.setObjectName("dockWidget_parameter_enum")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView_parameter_enum = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treeView_parameter_enum.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView_parameter_enum.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeView_parameter_enum.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView_parameter_enum.setObjectName("treeView_parameter_enum")
        self.verticalLayout.addWidget(self.treeView_parameter_enum)
        self.dockWidget_parameter_enum.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_parameter_enum)
        self.actionCommit = QtWidgets.QAction(MainWindow)
        self.actionCommit.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCommit.setIcon(icon)
        self.actionCommit.setObjectName("actionCommit")
        self.actionRollback = QtWidgets.QAction(MainWindow)
        self.actionRollback.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/nok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRollback.setIcon(icon1)
        self.actionRollback.setObjectName("actionRollback")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionClose.setObjectName("actionClose")
        self.actionAdd_object_classes = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/plus_object_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_object_classes.setIcon(icon3)
        self.actionAdd_object_classes.setObjectName("actionAdd_object_classes")
        self.actionAdd_objects = QtWidgets.QAction(MainWindow)
        self.actionAdd_objects.setIcon(icon3)
        self.actionAdd_objects.setObjectName("actionAdd_objects")
        self.actionAdd_relationship_classes = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/plus_relationship_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_relationship_classes.setIcon(icon4)
        self.actionAdd_relationship_classes.setObjectName("actionAdd_relationship_classes")
        self.actionAdd_relationships = QtWidgets.QAction(MainWindow)
        self.actionAdd_relationships.setIcon(icon4)
        self.actionAdd_relationships.setObjectName("actionAdd_relationships")
        self.actionImport = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/import_ds.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon5)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/export_ds.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon6)
        self.actionExport.setObjectName("actionExport")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon7)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon8)
        self.actionPaste.setObjectName("actionPaste")
        self.actionRemove_object_parameter_values = QtWidgets.QAction(MainWindow)
        self.actionRemove_object_parameter_values.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/minus_object_parameter_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_object_parameter_values.setIcon(icon9)
        self.actionRemove_object_parameter_values.setObjectName("actionRemove_object_parameter_values")
        self.actionRemove_relationship_parameter_values = QtWidgets.QAction(MainWindow)
        self.actionRemove_relationship_parameter_values.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/minus_relationship_parameter_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_relationship_parameter_values.setIcon(icon10)
        self.actionRemove_relationship_parameter_values.setObjectName("actionRemove_relationship_parameter_values")
        self.actionRemove_object_parameter_definitions = QtWidgets.QAction(MainWindow)
        self.actionRemove_object_parameter_definitions.setEnabled(False)
        self.actionRemove_object_parameter_definitions.setIcon(icon9)
        self.actionRemove_object_parameter_definitions.setObjectName("actionRemove_object_parameter_definitions")
        self.actionRemove_relationship_parameter_definitions = QtWidgets.QAction(MainWindow)
        self.actionRemove_relationship_parameter_definitions.setEnabled(False)
        self.actionRemove_relationship_parameter_definitions.setIcon(icon10)
        self.actionRemove_relationship_parameter_definitions.setObjectName("actionRemove_relationship_parameter_definitions")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon11)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionEdit_object_classes = QtWidgets.QAction(MainWindow)
        self.actionEdit_object_classes.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/edit_object_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_object_classes.setIcon(icon12)
        self.actionEdit_object_classes.setObjectName("actionEdit_object_classes")
        self.actionEdit_relationship_classes = QtWidgets.QAction(MainWindow)
        self.actionEdit_relationship_classes.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/edit_relationship_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_relationship_classes.setIcon(icon13)
        self.actionEdit_relationship_classes.setObjectName("actionEdit_relationship_classes")
        self.actionEdit_objects = QtWidgets.QAction(MainWindow)
        self.actionEdit_objects.setEnabled(False)
        self.actionEdit_objects.setIcon(icon12)
        self.actionEdit_objects.setObjectName("actionEdit_objects")
        self.actionEdit_relationships = QtWidgets.QAction(MainWindow)
        self.actionEdit_relationships.setEnabled(False)
        self.actionEdit_relationships.setIcon(icon13)
        self.actionEdit_relationships.setObjectName("actionEdit_relationships")
        self.actionRemove_object_tree_items = QtWidgets.QAction(MainWindow)
        self.actionRemove_object_tree_items.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/minus_object_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_object_tree_items.setIcon(icon14)
        self.actionRemove_object_tree_items.setObjectName("actionRemove_object_tree_items")
        self.actionManage_parameter_tags = QtWidgets.QAction(MainWindow)
        self.actionManage_parameter_tags.setObjectName("actionManage_parameter_tags")
        self.actionAdd_parameter_enums = QtWidgets.QAction(MainWindow)
        self.actionAdd_parameter_enums.setObjectName("actionAdd_parameter_enums")
        self.actionEdit_parameter_enums = QtWidgets.QAction(MainWindow)
        self.actionEdit_parameter_enums.setEnabled(False)
        self.actionEdit_parameter_enums.setObjectName("actionEdit_parameter_enums")
        self.actionRemove_parameter_enums = QtWidgets.QAction(MainWindow)
        self.actionRemove_parameter_enums.setEnabled(False)
        self.actionRemove_parameter_enums.setObjectName("actionRemove_parameter_enums")
        self.menuSession.addAction(self.actionRefresh)
        self.menuSession.addAction(self.actionCommit)
        self.menuSession.addAction(self.actionRollback)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_object_classes)
        self.menuEdit.addAction(self.actionAdd_objects)
        self.menuEdit.addAction(self.actionAdd_relationship_classes)
        self.menuEdit.addAction(self.actionAdd_relationships)
        self.menuEdit.addAction(self.actionEdit_object_classes)
        self.menuEdit.addAction(self.actionEdit_objects)
        self.menuEdit.addAction(self.actionEdit_relationship_classes)
        self.menuEdit.addAction(self.actionEdit_relationships)
        self.menuEdit.addAction(self.actionRemove_object_tree_items)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRemove_object_parameter_definitions)
        self.menuEdit.addAction(self.actionRemove_object_parameter_values)
        self.menuEdit.addAction(self.actionRemove_relationship_parameter_definitions)
        self.menuEdit.addAction(self.actionRemove_relationship_parameter_values)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_parameter_enums)
        self.menuEdit.addAction(self.actionEdit_parameter_enums)
        self.menuEdit.addAction(self.actionRemove_parameter_enums)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionManage_parameter_tags)
        self.menuEdit.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSession.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_object_parameter.setCurrentIndex(0)
        self.tabWidget_object_parameter_json.setCurrentIndex(0)
        self.tabWidget_relationship_parameter.setCurrentIndex(0)
        self.tabWidget_relationship_parameter_json.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.treeView_object, self.tabWidget_object_parameter)
        MainWindow.setTabOrder(self.tabWidget_object_parameter, self.tableView_object_parameter_value)
        MainWindow.setTabOrder(self.tableView_object_parameter_value, self.tabWidget_object_parameter_json)
        MainWindow.setTabOrder(self.tabWidget_object_parameter_json, self.textEdit_object_parameter_json)
        MainWindow.setTabOrder(self.textEdit_object_parameter_json, self.tableView_object_parameter_json)
        MainWindow.setTabOrder(self.tableView_object_parameter_json, self.pushButton_object_parameter_json_ok)
        MainWindow.setTabOrder(self.pushButton_object_parameter_json_ok, self.tableView_object_parameter_definition)
        MainWindow.setTabOrder(self.tableView_object_parameter_definition, self.tabWidget_relationship_parameter)
        MainWindow.setTabOrder(self.tabWidget_relationship_parameter, self.tableView_relationship_parameter_value)
        MainWindow.setTabOrder(self.tableView_relationship_parameter_value, self.tabWidget_relationship_parameter_json)
        MainWindow.setTabOrder(self.tabWidget_relationship_parameter_json, self.textEdit_relationship_parameter_json)
        MainWindow.setTabOrder(self.textEdit_relationship_parameter_json, self.tableView_relationship_parameter_json)
        MainWindow.setTabOrder(self.tableView_relationship_parameter_json, self.pushButton_relationship_parameter_json_ok)
        MainWindow.setTabOrder(self.pushButton_relationship_parameter_json_ok, self.tableView_relationship_parameter_definition)
        MainWindow.setTabOrder(self.tableView_relationship_parameter_definition, self.treeView_parameter_enum)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_object_tree.setText(QtWidgets.QApplication.translate("MainWindow", "Object tree", None, -1))
        self.treeView_object.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "object tree", None, -1))
        self.tableView_object_parameter_value.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "object parameter value", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "JSON editor", None, -1))
        self.tabWidget_object_parameter_json.setTabText(self.tabWidget_object_parameter_json.indexOf(self.json_obj), QtWidgets.QApplication.translate("MainWindow", "{ }", None, -1))
        self.label_object_parameter_json_error.setText(QtWidgets.QApplication.translate("MainWindow", "err", None, -1))
        self.tabWidget_object_parameter_json.setTabText(self.tabWidget_object_parameter_json.indexOf(self.json_arr), QtWidgets.QApplication.translate("MainWindow", "[ ]", None, -1))
        self.pushButton_object_parameter_json_ok.setText(QtWidgets.QApplication.translate("MainWindow", "Ok", None, -1))
        self.tabWidget_object_parameter.setTabText(self.tabWidget_object_parameter.indexOf(self.tab_object_parameter_value), QtWidgets.QApplication.translate("MainWindow", "value", None, -1))
        self.tableView_object_parameter_definition.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "object parameter definition", None, -1))
        self.tabWidget_object_parameter.setTabText(self.tabWidget_object_parameter.indexOf(self.tab_object_parameter_definition), QtWidgets.QApplication.translate("MainWindow", "definition", None, -1))
        self.tableView_relationship_parameter_value.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "relationship parameter value", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "JSON editor", None, -1))
        self.tabWidget_relationship_parameter_json.setTabText(self.tabWidget_relationship_parameter_json.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "{ }", None, -1))
        self.label_relationship_parameter_json_error.setText(QtWidgets.QApplication.translate("MainWindow", "err", None, -1))
        self.tabWidget_relationship_parameter_json.setTabText(self.tabWidget_relationship_parameter_json.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "[ ]", None, -1))
        self.pushButton_relationship_parameter_json_ok.setText(QtWidgets.QApplication.translate("MainWindow", "Ok", None, -1))
        self.tabWidget_relationship_parameter.setTabText(self.tabWidget_relationship_parameter.indexOf(self.tab_relationship_parameter_value), QtWidgets.QApplication.translate("MainWindow", "value", None, -1))
        self.tableView_relationship_parameter_definition.setAccessibleName(QtWidgets.QApplication.translate("MainWindow", "relationship parameter definition", None, -1))
        self.tabWidget_relationship_parameter.setTabText(self.tabWidget_relationship_parameter.indexOf(self.tab_relationship_parameter_definition), QtWidgets.QApplication.translate("MainWindow", "definition", None, -1))
        self.menuSession.setTitle(QtWidgets.QApplication.translate("MainWindow", "Session", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuToolbars.setTitle(QtWidgets.QApplication.translate("MainWindow", "Toolbars", None, -1))
        self.dockWidget_parameter_enum.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Parameter enum", None, -1))
        self.actionCommit.setText(QtWidgets.QApplication.translate("MainWindow", "Commit", None, -1))
        self.actionCommit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Return", None, -1))
        self.actionRollback.setText(QtWidgets.QApplication.translate("MainWindow", "Rollback", None, -1))
        self.actionRollback.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Backspace", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))
        self.actionClose.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None, -1))
        self.actionAdd_object_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Add object classes", None, -1))
        self.actionAdd_object_classes.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add object classes", None, -1))
        self.actionAdd_object_classes.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+O", None, -1))
        self.actionAdd_objects.setText(QtWidgets.QApplication.translate("MainWindow", "Add objects", None, -1))
        self.actionAdd_objects.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add objects", None, -1))
        self.actionAdd_objects.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionAdd_relationship_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Add relationship classes", None, -1))
        self.actionAdd_relationship_classes.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add relationship classes", None, -1))
        self.actionAdd_relationship_classes.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+R", None, -1))
        self.actionAdd_relationships.setText(QtWidgets.QApplication.translate("MainWindow", "Add relationships", None, -1))
        self.actionAdd_relationships.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add relationships", None, -1))
        self.actionAdd_relationships.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.actionImport.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I", None, -1))
        self.actionExport.setText(QtWidgets.QApplication.translate("MainWindow", "Export", None, -1))
        self.actionExport.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.actionConnect.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.actionCopy.setText(QtWidgets.QApplication.translate("MainWindow", "Copy", None, -1))
        self.actionCopy.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+C", None, -1))
        self.actionPaste.setText(QtWidgets.QApplication.translate("MainWindow", "Paste", None, -1))
        self.actionPaste.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+V", None, -1))
        self.actionRemove_object_parameter_values.setText(QtWidgets.QApplication.translate("MainWindow", "Remove object parameter values", None, -1))
        self.actionRemove_relationship_parameter_values.setText(QtWidgets.QApplication.translate("MainWindow", "Remove relationship parameter values", None, -1))
        self.actionRemove_object_parameter_definitions.setText(QtWidgets.QApplication.translate("MainWindow", "Remove object parameter definitions", None, -1))
        self.actionRemove_relationship_parameter_definitions.setText(QtWidgets.QApplication.translate("MainWindow", "Remove relationship parameter definitions", None, -1))
        self.actionRefresh.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.actionRefresh.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+Return", None, -1))
        self.actionEdit_object_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Edit object classes", None, -1))
        self.actionEdit_relationship_classes.setText(QtWidgets.QApplication.translate("MainWindow", "Edit relationship classes", None, -1))
        self.actionEdit_objects.setText(QtWidgets.QApplication.translate("MainWindow", "Edit objects", None, -1))
        self.actionEdit_relationships.setText(QtWidgets.QApplication.translate("MainWindow", "Edit relationships", None, -1))
        self.actionRemove_object_tree_items.setText(QtWidgets.QApplication.translate("MainWindow", "Remove object tree items", None, -1))
        self.actionManage_parameter_tags.setText(QtWidgets.QApplication.translate("MainWindow", "Manage parameter tags", None, -1))
        self.actionManage_parameter_tags.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+T", None, -1))
        self.actionAdd_parameter_enums.setText(QtWidgets.QApplication.translate("MainWindow", "Add parameter enums", None, -1))
        self.actionEdit_parameter_enums.setText(QtWidgets.QApplication.translate("MainWindow", "Edit parameter enum", None, -1))
        self.actionRemove_parameter_enums.setText(QtWidgets.QApplication.translate("MainWindow", "Remove parameter enums", None, -1))

from widgets.custom_qtreeview import ObjectTreeView
from widgets.custom_qtableview import CopyPasteTableView, AutoFilterCopyPasteTableView
import resources_icons_rc
